#!/bin/bash

if [[ ! $# -eq 1 ]]
  then
  echo -e "\e[95mBruh\e[0m you needa have just one argument. C'mon now."
else
  infile=$1
  if [[ $infile =~ .\.svg$ ]]
    then                              # Output Styles listed here:

    # 1. Print input file name
    echo -en "\e[4m"                  # 1. Underline
    inlen=$(cat $infile | wc -l)
    echo -e "Input: \"$infile\" ($inlen lines)"
    
    # 2. Show input file
    echo -en "\e[24;96m"              # 2. Cyan, no Underline
    # if [[ $inlen -gt 15 ]] 
    #   then
    #   cat $infile | head -n 10
    #   echo ...
    #   cat $infile | tail -n 5
    # else
      cat $infile
    # fi
    
    # 3. Convert to GCode
    echo -e "\e[0;4m"                  # 4. White, Underlined
    buglen=$(python -c "import svg2gcode as s2g; s2g.generate_gcode(\"$infile\")" | wc -l)
    echo "Debugging: ($buglen line)"
    echo -en "\e[24;33m"               # 5. Orange, no Underline
    python -c "import svg2gcode as s2g; s2g.generate_gcode(\"$infile\")"
    
    # 4. Print output file name
    echo -e "\e[0;4m"                  # 4. White, Underlined
    fname=${infile%.svg}
    outfile=${fname//in\//out\/}.gcode
    outlen=$(cat $outfile | wc -l)
    echo -e "Output: \"$outfile\" ($outlen lines)"


    # 5. Print output file
    echo -en "\e[24;32m"               # 5. Green, no Underline
    # if [[ $outlen -gt 15 ]] 
    #   then
    #   cat $outfile | head -n 10
    #   echo ...
    #   cat $outfile | tail -n 5
    # else
        cat $outfile
    # fi
    
    echo -ne "\e[0m"                   # Reset to normal
  else 
    echo -e "\e[31mNa.\e[0m That's not an svg file!"
  fi
fi
